### ISSUE TITLE
Interfaces

### ISSUE THREAD

**Issue by drigberg** [drigberg/nerdata#5]
## DESCRIPTION
We need interfaces all over the place!

## DETAILS
- We should be able to safely assert types when reading from json files, since they're tested with schema validation. I wouldn't be opposed to type guards, as long as we don't introduce any more dependencies (ex: joi outside of testing)

## DEFINITION OF DONE
- [x] `any` is used as little as possible, if ever
- [x] type guards are introduced when accepting user input
- [x] new validation is tested
- [x] tests pass
- [x] code compiles with no errors
- [x] PR is reviewed

**Comment by dpsmith3** [comment]
Can I help with this?

**Comment by drigberg** [comment]
Absolutely!

Here's my current PR for this issue: https://github.com/drigberg/nerdata/pull/11

It would be great if you could continue on this branch, or branch off from it!

**Comment by dpsmith3** [comment]
Hi Daniel,

Thanks for this.

Unfortunately my week became very busy, so I haven't had a chance to work on this yet - sorry. I'll certainly take a look at the weekend and see if there's something I can help out with.

Cheers,

Dan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
